package analyser

func init() {
	// a dumb map between the searchable string, and some keywords to find in the tweet
	sections := make(map[string][]string)

	sections["gay rights"] = []string{"gay", "lesbian", "LGB", "LGBT"}
	sections["smoking bans"] = []string{"smoking ban"}
	sections["marriage"] = []string{"gay marriage", "marriage", "same sex"} // allowing marriage between two people of same sex
	sections["equality and human rights"] = []string{"equality", "human rights"}
	sections["terminally ill people assistance to end their life"] = []string{"euthenasia"}
	sections["UK military forces"] = []string{"military intervention", "peacekeeping"} //use of UK military forces in combat operations overseas
	sections["investigations"] = []string{"iraq", "iraq war"}                          //investigations into the Iraq war
	sections["Trident"] = []string{"trident", "WMD", "nuclear weapons"}
	sections["EU integration"] = []string{"eu integration"}       // eu integration
	sections["EU"] = []string{"eu referendum"}                    //referendum on the UK's membership of the EU
	sections["Military Covenant"] = []string{"Military Covenant"} //strengthening the Military Covenant
	sections["right to remain for EU nationals"] = []string{"EU national", "right to remain"}
	sections["UK membership of the EU"] = []string{"EU", "brexit"}
	sections["military action against ISIL (Daesh)"] = []string{"ISIL"}
	sections["housing benefit"] = []string{"bedroom tax", "housing benefit"} // bedroom tax
	sections["welfare benefits"] = []string{"welfare", "benefits"}           //raising welfare benefits at least in line with prices
	sections["illness or disability"] = []string{"disability benefits"}      //paying higher benefits over longer periods for those unable to work due to illness or disability
	sections["financial need council tax"] = []string{}                      //making local councils responsible for helping those in financial need afford their council tax and reducing the amount spent on such support
	sections["welfare benefits"] = []string{}
	sections["guaranteed jobs for young people"] = []string{}
	sections["income tax"] = []string{}
	sections["rate of VAT"] = []string{}
	sections["alcoholic drinks"] = []string{}
	sections["taxes on plane tickets"] = []string{}
	sections["fuel for motor vehicles"] = []string{}
	sections["income over £150,000"] = []string{}
	sections["occupational pensions"] = []string{}
	sections["occupational pensions"] = []string{}
	sections["banker’s bonus tax"] = []string{}
	sections["taxes on banks"] = []string{}
	sections["mansion tax"] = []string{}
	sections["rights for shares"] = []string{}
	sections["regulation of trade union activity"] = []string{}
	sections["capital gains tax"] = []string{}
	sections["corporation tax"] = []string{}
	sections["tax avoidance"] = []string{}
	sections["incentives for companies to invest"] = []string{}
	sections["high speed rail"] = []string{}
	sections["private patients"] = []string{}
	sections["NHS"] = []string{}
	sections["smoking bans"] = []string{}
	sections["terminally ill people assistance to end their life"] = []string{}
	sections["autonomy for schools"] = []string{}
	sections["undergraduate tuition fee"] = []string{}
	sections["academy schools"] = []string{}
	sections["financial support"] = []string{}
	sections["tuition fees"] = []string{}
	sections["funding of local government"] = []string{}
	sections["equal number of electors"] = []string{}
	sections["fewer MPs"] = []string{}
	sections["proportional system"] = []string{}
	sections["wholly elected"] = []string{}
	sections["taxes on business premises"] = []string{}
	sections["campaigning by third parties"] = []string{}
	sections["fixed periods between parliamentary elections"] = []string{}
	sections["hereditary peers"] = []string{}
	sections["more powers to the Welsh Assembly"] = []string{}
	sections["more powers to the Scottish Parliament"] = []string{}
	sections["powers for local councils"] = []string{}
	sections["a veto for MPs over laws specifically impacting their part of the UK"] = []string{}
	sections["voting age"] = []string{}
	sections["stricter asylum system"] = []string{}
	sections["Police and Crime Commissioners"] = []string{}
	sections["retention of information about communications"] = []string{}
	sections["enforcement of immigration rules"] = []string{}
	sections["mass surveillance"] = []string{}
	sections["merging police and fire services"] = []string{}
	sections["prevent climate change"] = []string{}
	sections["fuel for motor vehicles"] = []string{}
	sections["forests"] = []string{}
	sections["taxes on plane tickets"] = []string{}
	sections["low carbon electricity generation"] = []string{}
	sections["culling badgers"] = []string{}
	sections["hydraulic fracturing (fracking)"] = []string{}
	sections["high speed rail"] = []string{}
	sections["bus services"] = []string{}
	sections["rail fares"] = []string{}
	sections["fuel for motor vehicles"] = []string{}
	sections["taxes on plane tickets"] = []string{}
	sections["publicly owned railway system"] = []string{}
	sections["secure tenancies for life"] = []string{}
	sections["market rent to high earners renting a council home"] = []string{}
	sections["regulation of gambling"] = []string{}
	sections["civil service redundancy payments"] = []string{}
	sections["anti-terrorism laws"] = []string{}
	sections["Royal Mail"] = []string{}
	sections["pub landlords rent-only leases"] = []string{}
	sections["legal aid"] = []string{}
	sections["courts in secret sessions"] = []string{}
	sections["register of lobbyists"] = []string{}
	sections["fees no-win no fee cases"] = []string{}
	sections["fees letting agents"] = []string{}
	sections["Conservative - Liberal Democrat Coalition Agreement"] = []string{}
}
